# Generated by Django 2.2.3 on 2019-09-30 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('door_step', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package_tracking',
            old_name='Activity',
            new_name='Billng_Activity',
        ),
        migrations.RenameField(
            model_name='package_tracking',
            old_name='Details',
            new_name='Current_Location',
        ),
        migrations.RenameField(
            model_name='package_tracking',
            old_name='Location',
            new_name='Package_status',
        ),
        migrations.RenameField(
            model_name='package_tracking',
            old_name='status',
            new_name='Payment_Details',
        ),
        migrations.RenameField(
            model_name='package_tracking',
            old_name='Last_Name',
            new_name='Receiver_Last_Name',
        ),
        migrations.RenameField(
            model_name='package_tracking',
            old_name='Sender',
            new_name='Sender_Name',
        ),
    ]
